"""
app.ai.ollama.response_parser — Parses structured LLM responses into strongly typed objects.

Enforces schemas and extracts command lists, explanations, and risk level keys.
"""

from __future__ import annotations

import json
import logging
from dataclasses import dataclass, field
from typing import List, Optional

logger = logging.getLogger("ResponseParser")


@dataclass
class RemediationReport:
    """Strongly typed mitigation advice generated by local LLM."""
    threat_summary: str = "No threat summary available."
    reasoning: str = "No reasoning provided."
    recommended_actions: List[str] = field(default_factory=list)
    linux_commands: List[str] = field(default_factory=list)
    rollback_commands: List[str] = field(default_factory=list)
    risk_level: str = "LOW"
    additional_notes: str = ""


class ResponseParser:
    """Parses and sanitizes LLM JSON output strings into RemediationReport objects."""

    @staticmethod
    def parse_response(raw_text: str) -> RemediationReport:
        """
        Sanitize and parse JSON response. Falls back gracefully on error.
        """
        if not raw_text or not raw_text.strip():
            return RemediationReport(threat_summary="Local AI returned empty response.")

        clean_text = raw_text.strip()

        # Find the first '{' and last '}' to extract the JSON block
        start_idx = clean_text.find("{")
        end_idx = clean_text.rfind("}")
        if start_idx != -1 and end_idx != -1 and end_idx > start_idx:
            clean_text = clean_text[start_idx:end_idx + 1].strip()

        try:
            parsed = json.loads(clean_text)
            
            # Map dictionary safely with defaults
            report = RemediationReport(
                threat_summary=parsed.get("threat_summary", "No summary provided by AI."),
                reasoning=parsed.get("reasoning", "No reasoning provided."),
                recommended_actions=parsed.get("recommended_actions") or [],
                linux_commands=parsed.get("linux_commands") or [],
                rollback_commands=parsed.get("rollback_commands") or [],
                risk_level=str(parsed.get("risk_level", "LOW")).upper(),
                additional_notes=parsed.get("additional_notes", "")
            )
            return report
        except json.JSONDecodeError as exc:
            logger.error(f"Failed to decode JSON from Ollama response: {exc}. Raw: {raw_text}")
            # Try to build a heuristic fallback if parsing failed
            return RemediationReport(
                threat_summary="Failed to parse structured response from Ollama.",
                reasoning=f"JSON parsing error: {exc}",
                additional_notes=raw_text[:200] + "..." if len(raw_text) > 200 else raw_text
            )
        except Exception as exc:
            logger.error(f"Unexpected error mapping LLM response: {exc}")
            return RemediationReport(
                threat_summary="Unexpected error while loading LLM results."
            )
